### ISSUE TITLE
panic: unexpected status code: 400

### ISSUE THREAD

**Issue by xihajun** [appleboy/whisper-action#2]
```
panic: unexpected status code: 400

goroutine 1 [running]:
github.com/appleboy/go-whisper/youtube.(*Engine).download(0xc0004875b8, {0xd4bbe0, 0x14a2b80}, {0xd45980?, 0xc0001e3b80})
	/app/youtube/youtube.go:86 +0x418
github.com/appleboy/go-whisper/youtube.(*Engine).Download(0xc0004875b8, {0xd4bbe0, 0x14a2b80})
	/app/youtube/youtube.go:[62](https://github.com/boringresearch/micrograd/actions/runs/8458617197/job/23173251699#step:4:63) +0x285
main.run(0xc000268160?)
	/app/main.go:242 +0xa70
github.com/urfave/cli/v2.(*Command).Run(0xc000268160, 0xc000171780, {0xc000120060, 0x1, 0x1})
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/command.go:279 +0x9dd
github.com/urfave/cli/v2.(*App).RunContext(0xc0001b8200, {0xd4bbe0?, 0x14a2b80}, {0xc000120060, 0x1, 0x1})
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:337 +0x5db
github.com/urfave/cli/v2.(*App).Run(...)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.27.1/app.go:311
main.main()
	/app/main.go:185 +0x18d0
```

**Comment by NeddM** [comment]
Same problem here, looks like it's a problem about downloading the video from YouTube.
